[workspace]
members  = ["crates/fs-store", "crates/fs-store-app", "crates/fs-store-cli"]
resolver = "2"

[workspace.package]
version    = "0.1.0"
edition    = "2021"
license    = "MIT"
authors    = ["FreeSynergy.Net"]
repository = "https://github.com/FreeSynergy/fs-store"

[workspace.dependencies]
# Workspace crates
fs-store  = { path = "crates/fs-store" }
fs-render = { path = "../fs-render" }
fs-i18n   = { path = "../fs-i18n" }

# Serde
serde      = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
toml       = { version = "1", features = ["preserve_order"] }

# Error handling
anyhow    = { version = "1" }
thiserror = { version = "2" }

# Async
tokio       = { version = "1", features = ["full"] }
async-trait = { version = "0.1" }

# HTTP
reqwest = { version = "0.13", features = ["json", "rustls"], default-features = false }

# Logging
tracing            = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# CLI
clap = { version = "4", features = ["derive", "env"] }

# Time
chrono = { version = "0.4", features = ["serde"] }

# GUI
dioxus         = { version = "0.7.3", default-features = false, features = ["macro", "html", "signals", "hooks", "launch", "document"] }
dioxus-desktop = { path = "../fs-desktop/vendor/dioxus-desktop" }
