[package]
name        = "fs-store-app"
description = "FreeSynergy Store — GUI + CLI entry point"
version.workspace   = true
edition.workspace   = true
license.workspace   = true
authors.workspace   = true
repository.workspace = true

[[bin]]
name = "fs-store"
path = "src/main.rs"

[dependencies]
fs-store       = { workspace = true }
tokio          = { workspace = true }
tracing        = { workspace = true }
anyhow         = { workspace = true }
dioxus         = { workspace = true }
dioxus-desktop = { workspace = true }
